adding hybridization change filter
OpenFreeEnergy/kartograf pull request #35
Opened 2024-01-29 23:02 UTC by RiesBen

This PR adds a filter for hybridization_changes of atoms, disallowing them.

- [ ] general hybridization changes
- [ ] ring hybridization changes.

2024-01-29 23:02 UTC, pep8speaks commented
Hello @RiesBen! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`src/kartograf/filters/element_change.py`](https://github.com/OpenFreeEnergy/kartograf/blob/b4c0112dea770802101af2d0e6c391a433f4eaf2/src/kartograf/filters/element_change.py):

> [Line 57:80](https://github.com/OpenFreeEnergy/kartograf/blob/b4c0112dea770802101af2d0e6c391a433f4eaf2/src/kartograf/filters/element_change.py#L57): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 68:28](https://github.com/OpenFreeEnergy/kartograf/blob/b4c0112dea770802101af2d0e6c391a433f4eaf2/src/kartograf/filters/element_change.py#L68): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`src/kartograf/tests/test_element_filters.py`](https://github.com/OpenFreeEnergy/kartograf/blob/b4c0112dea770802101af2d0e6c391a433f4eaf2/src/kartograf/tests/test_element_filters.py):

> [Line 42:1](https://github.com/OpenFreeEnergy/kartograf/blob/b4c0112dea770802101af2d0e6c391a433f4eaf2/src/kartograf/tests/test_element_filters.py#L42): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2024-01-30 17:58 UTC, richardjgowers requested changes
this is good, would it also make sense to have a cyclohexane to benzene test too?

2024-01-30 17:58 UTC, richardjgowers commented on src/kartograf/tests/test_element_filters.py
> +    # benzene to pyridine, has heteroatom change
this comment seems wrong?

2024-01-30 17:58 UTC, richardjgowers commented on src/kartograf/filters/element_change.py
> +    """Forces a mapping to exclude any alchemical hybridization changes."""
can we add another quick line giving examples of what it would filter, e.g. your `-CC >> -C=C` test in words here

2024-01-30 18:35 UTC, RiesBen commented on src/kartograf/tests/test_element_filters.py
> +    # benzene to pyridine, has heteroatom change
oh ups!

2024-01-30 18:39 UTC, RiesBen commented
@richardjgowers yes that is a very important change even. but we would need to check the all ring atoms, I think. Therefore this would be a ring -change filter.

2024-01-30 18:50 UTC, richardjgowers approved these changes

2024-01-30 18:50 UTC, merged